services:
  backend:
    image: 'btradebackend'
    ports:
      - "20000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://sorayutchroenrit:ZUwGGkFh0ikC9CWx@bondtraderdb.i6rc0pn.mongodb.net/
  
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure