services:
  backend:
    image: 'btradebackend'
    ports:
      - "20000:20000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/BONDTRADER_DB
  
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: