version: '3'

services:
  backend:
    image: 'btradebackend'
    container_name: btradebackend-run
    ports:
      - "20000:20000"
    environment:
      - MONGODB_URI=mongodb+srv://sorayutchroenrit:ZUwGGkFh0ikC9CWx@bondtraderdb.i6rc0pn.mongodb.net/BONDTRADER_DB
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - btrader-network

  frontend:
    build: .
    container_name: btradefrontend-run
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:20000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=BOND_FRONT_SECRET
    depends_on:
      - backend
    restart: on-failure
    networks:
      - btrader-network

networks:
  btrader-network:
    driver: bridge